### ISSUE TITLE
cannot add new time period to Pleiades settings

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#498]
Steps to reproduce:

- Login to the Pleiades plone with an account with admin privileges
- Navigate to `@@pleiades-settings`
- Scroll to the bottom of the "Time Periods" table and enter this data in the new line:

| Id | Title | Description | Lower | Upper | Same As |
| --- | --- | --- | --- | --- | --- |
| parthian | Parthian (200 BCE - 224 CE) | -200 | 224 | The period of Parthian expansion and hegemony in southwest Asia and beyond | http://n2t.net/ark:/99152/p08m57hs35q |

- Scroll to the bottom of the page and click the "save" button. 
- Wait for the page to save and reload, then check for the new time period. You will not find it.

**Comment by silviot** [comment]
I think when I deployed the addition of the Zotero `default_works` I made a mistake, and used the debug console to add the registry with a command like this:

```
app.plone.portal_registry._records._values["pleiades.vocabularies.interfaces.IPleiadesSettings.default_works"] = [{'short_title': u'New Pauly',
  'zotero_uri': 'https://www.zotero.org/groups/2533/items/DUTS58MJ'},
 {'short_title': u'RE',
  'zotero_uri': 'https://www.zotero.org/groups/2533/items/HSGNAEBR'},
 {'short_title': u'BAtlas',
  'zotero_uri': 'https://www.zotero.org/groups/2533/items/MIAGQ5C6'},
 {'short_title': u'BAtlDir',
  'zotero_uri': 'https://www.zotero.org/groups/2533/items/9377UUFB'},
 {'short_title': u'Wikipedia (English)',
  'zotero_uri': 'https://www.zotero.org/groups/2533/items/CI6F6W7W'},
 {'short_title': u'Wikipedia (Greek)',
  'zotero_uri': 'https://www.zotero.org/groups/2533/items/BUR4V79V'},
 {'short_title': u'Wikipedia (French)',
  'zotero_uri': 'https://www.zotero.org/groups/2533/items/B4HPCZIK'},
 {'short_title': u'Wikipedia (German)',
  'zotero_uri': 'https://www.zotero.org/groups/2533/items/QVRBJVTM'},
 {'short_title': u'Wikipedia (Italian)',
  'zotero_uri': 'https://www.zotero.org/groups/2533/items/UMFZH98D'},
 {'short_title': u'Wikidata',
  'zotero_uri': 'https://www.zotero.org/groups/2533/items/BCQIKDKS'},
 {'short_title': u'TP (Talbert: CUP)',
  'zotero_uri': 'https://www.zotero.org/groups/2533/items/QT8GLGGI'},
 {'short_title': u'Str. (Meineke: Perseus)',
  'zotero_uri': 'https://www.zotero.org/groups/2533/items/FEVTVBA7'},
 {'short_title': u'Roller 2022',
  'zotero_uri': 'https://www.zotero.org/groups/2533/items/CMCPFLWG'},
 {'short_title': u'Basarrate 2022',
  'zotero_uri': 'https://www.zotero.org/groups/2533/items/XFWEA9BC'}]
```

I investigated now, and found out that the entry `app.plone.portal_registry._records._fields["pleiades.vocabularies.interfaces.IPleiadesSettings.default_works"]` was missing. I think its absence was interfering with the behavior of the form.

So I undid my change and imported the profile through the ZMI as I should probably have done from the start.

```
import pleiades.vocabularies.interfaces
del app.plone.portal_registry._records._values["pleiades.vocabularies.interfaces.IPleiadesSettings.default_works"]
app.plone.portal_registry.registerInterface(pleiades.vocabularies.interfaces.IPleiadesSettings)
```

but unfortunately this did not solve the original problem as I hoped.

As an interim solution to the immediate problem I ran this code to add the desired item:

```
app.plone.portal_registry._records["pleiades.vocabularies.interfaces.IPleiadesSettings.time_periods"]._set_value(app.plone.portal_registry._records["pleiades.vocabularies.interfaces.IPleiadesSettings.time_periods"].value + [{'description': u'The period of Parthian expansion and hegemony in southwest Asia and beyond', 'upper_bound': -200, 'title': u'Parthian (200 BCE - 224 CE)', 'lower_bound': 224, 'same_as': "http://n2t.net/ark:/99152/p08m57hs35q", 'hidden': False, 'id': u'parthian'}])
```

**Comment by paregorios** [comment]
@silviot thanks for working on this and for programmatically adding the "parthian" time period. Since whatever the problem is is still currently blocking us from making any changes to any of our vocabularies, this problem remains high priority for us. Thanks.

**Comment by silviot** [comment]
@paregorios I think I understand what's going on now. The last empty row in each table should not be there, and will not be considered in the form submission. To add a new row you need to click on the `+` button. That's quite a confusing UX. It's probably a bug in the formlib handling of array data.

**Comment by paregorios** [comment]
@silviot I see that that technique seems to work now; I will test rigorously. I find this odd; I've been using this form for years and have never observed this problem until now. But if I can make it work this way, I'm fine with that. I will test all my problems rigorously and report back.

**Comment by paregorios** [comment]
This is working on production.
